name: outlyer-angular
services:
  mongo:
    image: mongo:6
    container_name: mongo-angular
    command: [ "--quiet" ]
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - mongo-angular-data:/data/db
    ports:
      - "27018:27017" # Keep the same published port or change it if you want side-by-side
    networks:
      - quantum-angular-net

  quantum-angular:
    build:
      context: ../ # Context needs to be the root so Docker can access both /node and /frontend
      dockerfile: docker/Dockerfile.Angular
      args:
        GIT_BRANCH: ${GIT_BRANCH:-unknown}
        GIT_COMMIT: ${GIT_COMMIT:-unknown}
        APP_VERSION: ${APP_VERSION:-unknown}
    image: outlyer/quantum-angular
    container_name: quantum-angular
    restart: unless-stopped
    depends_on:
      mongo:
        condition: service_healthy
    env_file:
      - ../secrets.env
    environment:
      - SERVE_ANGULAR=true
    ports:
      - "3000:3000"
    networks:
      - quantum-angular-net

volumes:
  mongo-angular-data:


networks:
  quantum-angular-net:
    driver: bridge
